name: mpileup_call_pipeline
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.12
  - pandas=2.3.3
  - samblaster=0.1.26
  - snakemake=9.13.7
  - snakemake-executor-plugin-slurm=1.9.2
  - bcftools=1.22
  - matplotlib=3.10.8
  - minimap2=2.30
  - multiqc=1.32
  - numpy=2.3.5
  - samtools=1.22.1
  - tectonic=0.15.0
  - trim-galore=0.6.10